use std::path::{Path, PathBuf};
use std::process::Command;

// Base URL hosting the tool archives. Override at runtime with STE_TOOLS_URL.
// Upload archives generated by ./pack-tools.sh to this location.
const DEFAULT_TOOLS_URL: &str = "https://example.com/subextractor/tools";

struct ToolSpec {
    name: &'static str,
    file: &'static str,
}

const TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "ffmpeg",
        file: "ffmpeg.tar.gz",
    },
    ToolSpec {
        name: "demucs",
        file: "demucs.tar.gz",
    },
    ToolSpec {
        name: "youtubeuploader",
        file: "youtubeuploader.tar.gz",
    },
];

/// Download + extract missing tools into `<data_dir>/tools` in the background,
/// so app startup is never blocked by a large first-run download. Each tool is
/// gated by a `.<name>.installed` marker: if it exists, the tool is skipped.
pub fn ensure_tools(data_dir: &Path) {
    let tools_dir = data_dir.join("tools");
    if std::fs::create_dir_all(&tools_dir).is_err() {
        return;
    }
    let base_url = std::env::var("STE_TOOLS_URL")
        .unwrap_or_else(|_| DEFAULT_TOOLS_URL.to_string());
    std::thread::spawn(move || {
        for spec in TOOLS {
            let marker = tools_dir.join(format!(".{}.installed", spec.name));
            if marker.exists() {
                continue;
            }
            match install_tool(&tools_dir, &base_url, spec) {
                Ok(()) => println!("[tools] {} ready", spec.name),
                Err(e) => eprintln!("[tools] {} install failed: {e}", spec.name),
            }
        }
    });
}

/// Directory that holds the runtime tools (ffmpeg, demucs, youtubeuploader).
/// In dev, tools come from the repo source; in release, from the data dir
/// where ensure_tools() downloads them on first launch.
pub fn tools_dir(base: &Path, data_dir: &Path) -> PathBuf {
    if cfg!(debug_assertions) {
        let dev = base.join("src-tauri/resources/tools");
        if dev.join("ffmpeg").is_file() {
            return dev;
        }
    }
    data_dir.join("tools")
}

fn install_tool(tools_dir: &Path, base_url: &str, spec: &ToolSpec) -> Result<(), String> {
    let url = format!("{}/{}", base_url.trim_end_matches('/'), spec.file);
    let archive = tools_dir.join(format!("{}.tmp.tar.gz", spec.name));

    let status = Command::new("curl")
        .args(["-fL", "--retry", "3", "-o"])
        .arg(&archive)
        .arg(&url)
        .status()
        .map_err(|e| format!("curl: {e}"))?;
    if !status.success() {
        let _ = std::fs::remove_file(&archive);
        return Err(format!("download failed: {url}"));
    }

    let status = Command::new("tar")
        .args(["-xzf"])
        .arg(&archive)
        .current_dir(tools_dir)
        .status()
        .map_err(|e| format!("tar: {e}"))?;
    let _ = std::fs::remove_file(&archive);
    if !status.success() {
        return Err("extract failed".into());
    }

    std::fs::write(
        tools_dir.join(format!(".{}.installed", spec.name)),
        "1",
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}
