use std::path::{Path, PathBuf};
use std::process::Command;
use tauri::{AppHandle, Emitter};

// Base URL hosting the tool archives. Override at runtime with STE_TOOLS_URL.
// Upload archives generated by ./pack-tools.sh to this location.
// If this is the placeholder URL, we skip download and use system tools instead.
const DEFAULT_TOOLS_URL: &str = "https://example.com/subextractor/tools";

struct ToolSpec {
    name: &'static str,
    file: &'static str,
}

const TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "ffmpeg",
        file: "ffmpeg.tar.gz",
    },
    ToolSpec {
        name: "demucs",
        file: "demucs.tar.gz",
    },
    ToolSpec {
        name: "youtubeuploader",
        file: "youtubeuploader.tar.gz",
    },
];

#[derive(Clone, serde::Serialize)]
struct ToolProgress {
    name: String,
    status: String, // "downloading", "extracting", "ready", "skipped", "error"
    message: String,
}

/// Check if a tool exists in system PATH.
fn system_tool_exists(name: &str) -> bool {
    Command::new("which")
        .arg(name)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Check if a tool binary exists in the tools directory.
fn tool_exists_in_dir(tools_dir: &Path, name: &str) -> bool {
    tools_dir.join(name).is_file()
}

/// Check if URL is the placeholder (not a real host).
fn is_placeholder_url(url: &str) -> bool {
    url.contains("example.com") || url.is_empty()
}

/// Download + extract missing tools into `<data_dir>/tools` in the background,
/// so app startup is never blocked by a large first-run download. Each tool is
/// gated by a `.<name>.installed` marker: if it exists, the tool is skipped.
///
/// Fallback strategy:
/// 1. If marker exists → skip
/// 2. If STE_TOOLS_URL is placeholder → check system PATH
/// 3. If real URL → download
/// 4. If download fails → log warning, feature disabled
pub fn ensure_tools(app: &AppHandle, data_dir: &Path) {
    let tools_dir = data_dir.join("tools");
    if std::fs::create_dir_all(&tools_dir).is_err() {
        return;
    }
    let base_url = std::env::var("STE_TOOLS_URL")
        .unwrap_or_else(|_| DEFAULT_TOOLS_URL.to_string());

    let app_handle = app.clone();
    std::thread::spawn(move || {
        let total = TOOLS.len();
        for (idx, spec) in TOOLS.iter().enumerate() {
            let marker = tools_dir.join(format!(".{}.installed", spec.name));
            if marker.exists() {
                let _ = app_handle.emit("tools-progress", ToolProgress {
                    name: spec.name.to_string(),
                    status: "skipped".to_string(),
                    message: format!("{}/{} {} already installed", idx + 1, total, spec.name),
                });
                continue;
            }

            // If no real download URL configured, check tools dir + system PATH
            if is_placeholder_url(&base_url) {
                if tool_exists_in_dir(&tools_dir, spec.name) || system_tool_exists(spec.name) {
                    let _ = std::fs::write(&marker, "1");
                    println!("[tools] {} ready", spec.name);
                    let _ = app_handle.emit("tools-progress", ToolProgress {
                        name: spec.name.to_string(),
                        status: "ready".to_string(),
                        message: format!("{}/{} {} ready", idx + 1, total, spec.name),
                    });
                } else {
                    println!(
                        "[tools] {} not found — feature requiring {} will be disabled",
                        spec.name, spec.name
                    );
                    let _ = app_handle.emit("tools-progress", ToolProgress {
                        name: spec.name.to_string(),
                        status: "skipped".to_string(),
                        message: format!("{}/{} {} not found (optional)", idx + 1, total, spec.name),
                    });
                }
                continue;
            }

            // Try download from configured URL
            let _ = app_handle.emit("tools-progress", ToolProgress {
                name: spec.name.to_string(),
                status: "downloading".to_string(),
                message: format!("{}/{} Downloading {}...", idx + 1, total, spec.name),
            });

            match install_tool(&tools_dir, &base_url, spec) {
                Ok(()) => {
                    println!("[tools] {} ready", spec.name);
                    let _ = app_handle.emit("tools-progress", ToolProgress {
                        name: spec.name.to_string(),
                        status: "ready".to_string(),
                        message: format!("{}/{} {} ready", idx + 1, total, spec.name),
                    });
                }
                Err(e) => {
                    eprintln!("[tools] {} install failed: {e}", spec.name);
                    // Fallback: check system PATH if download fails
                    if system_tool_exists(spec.name) {
                        let _ = std::fs::write(&marker, "1");
                        println!("[tools] {} fallback to system PATH", spec.name);
                        let _ = app_handle.emit("tools-progress", ToolProgress {
                            name: spec.name.to_string(),
                            status: "ready".to_string(),
                            message: format!("{}/{} {} using system version", idx + 1, total, spec.name),
                        });
                    } else {
                        let _ = app_handle.emit("tools-progress", ToolProgress {
                            name: spec.name.to_string(),
                            status: "error".to_string(),
                            message: format!("{}/{} {} failed: {}", idx + 1, total, spec.name, e),
                        });
                    }
                }
            }
        }

        // All tools processed
        let _ = app_handle.emit("tools-progress", ToolProgress {
            name: "done".to_string(),
            status: "done".to_string(),
            message: "Environment setup complete".to_string(),
        });
    });
}

/// Directory that holds the runtime tools (ffmpeg, demucs, youtubeuploader).
/// In dev, tools come from the repo source; in release, from the data dir
/// where ensure_tools() downloads them on first launch.
pub fn tools_dir(base: &Path, data_dir: &Path) -> PathBuf {
    if cfg!(debug_assertions) {
        let dev = base.join("src-tauri/resources/tools");
        if dev.join("ffmpeg").is_file() {
            return dev;
        }
    }
    data_dir.join("tools")
}

fn install_tool(tools_dir: &Path, base_url: &str, spec: &ToolSpec) -> Result<(), String> {
    let url = format!("{}/{}", base_url.trim_end_matches('/'), spec.file);
    let archive = tools_dir.join(format!("{}.tmp.tar.gz", spec.name));

    let status = Command::new("curl")
        .args(["-fL", "--retry", "3", "-o"])
        .arg(&archive)
        .arg(&url)
        .status()
        .map_err(|e| format!("curl: {e}"))?;
    if !status.success() {
        let _ = std::fs::remove_file(&archive);
        return Err(format!("download failed: {url}"));
    }

    let status = Command::new("tar")
        .args(["-xzf"])
        .arg(&archive)
        .current_dir(tools_dir)
        .status()
        .map_err(|e| format!("tar: {e}"))?;
    let _ = std::fs::remove_file(&archive);
    if !status.success() {
        return Err("extract failed".into());
    }

    std::fs::write(
        tools_dir.join(format!(".{}.installed", spec.name)),
        "1",
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}
